export const COMMANDS = {
    eleTreeRefresh: 'eleTreeViewer.refresh',
    methodsRefresh: 'methodsViewer.refresh',
    pathFileRefresh: 'pathFileTree.refresh',
    pathSniffRefresh: 'pathSniffViewer.refresh',
    pathSniffToggleAutoRefresh: 'pathSniffViewer.toggleAutoRefresh',
    pathFileCreateCase: 'pathFileTree.createCase',
    pathFileOpenItem: 'pathFileTree.openItem',
    pathFileNewFile: 'pathFileTree.newFile',
    pathFileNewFolder: 'pathFileTree.newFolder',
    pathFileNewPythonPackage: 'pathFileTree.newPythonPackage',
    pathFileNewSniffBranch: 'pathFileTree.newSniffBranch',
    pathFileRename: 'pathFileTree.rename',
    pathFileDelete: 'pathFileTree.delete',
    pathFileRevealInOs: 'pathFileTree.revealInOS',
    pathFileCopyPath: 'pathFileTree.copyPath',
    pathFileCopyRelativePath: 'pathFileTree.copyRelativePath',
    pathFileFindInFolder: 'pathFileTree.findInFolder',
    pathFileCopyItem: 'pathFileTree.copyItem',
    pathFilePasteItem: 'pathFileTree.pasteItem',
    eleTreeDragToEditor: 'eleTreeViewer.dragToEditor',
    methodsDragToEditor: 'methodsViewer.dragToEditor',
    eleTreeSearch: 'eleTreeViewer.search',
    methodsSearch: 'methodsViewer.search',
    eleTreeClearSearch: 'eleTreeViewer.clearSearch',
    methodsClearSearch: 'methodsViewer.clearSearch',
    eleTreeOpenFile: 'eleTreeViewer.openFile',
    methodsOpenFile: 'methodsViewer.openFile',
    methodsJumpToMethod: 'methodsViewer.jumpToMethod',
    eleTreeOpenSecondaryView: 'eleTreeViewer.openSecondaryView',
    eleSecondaryFocus: 'eleSecondaryView.focus',
    eleTreeCreateCase: 'eleTreeViewer.createCase',
    eleTreeDebugMarkrunner: 'eleTreeViewer.debugMarkrunner',
    eleTreeAgentGeneration: 'eleTreeViewer.aiAgentGeneration',
    pathZentaoRefresh: 'pathZentaoTree.refresh',
    pathZentaoLogin: 'pathZentaoTree.login',
    pathZentaoLogout: 'pathZentaoTree.logout',
    pathZentaoOpenItem: 'pathZentaoTree.openItem'
} as const;

export type CommandId = (typeof COMMANDS)[keyof typeof COMMANDS];
